### ISSUE TITLE
BME 280 Qwiic Driver

### ISSUE THREAD

**Issue by gigapod** [sparkfun/pdp-qwiic-micro-python#1]
### Board

[SparkFun qwiic BME 280](https://www.sparkfun.com/products/15440)

### Notes

[Driver](https://github.com/sparkfun/Qwiic_BME280_Py)

**Comment by malcolm-sparkfun** [comment]
Looks good. Tested installing from mip with `mpremote mip install github:sparkfun/Qwiic_BME280_Py` and it appears to have properly installed the files for this package as well as the qwiic_i2c_py dependency package.
