### ISSUE TITLE
SparkFun Qwiic ToF Imager - VL53L5CX & Distance Sensor VL53L4CD

### ISSUE THREAD

**Issue by gigapod** [sparkfun/pdp-qwiic-micro-python#20]
### Boards

[SparkFun Qwiic ToF Imager](https://www.sparkfun.com/products/18642)
[SparkFun Distance Sensor - 1.3 Meter, VL53L4CD (Qwiic)](https://www.sparkfun.com/products/18993)

### Notes

* Existing [Driver](https://github.com/sparkfun/Qwiic_VL53L1X_Py)

**Comment by sfe-SparkFro** [comment]
Separating into different issues
