### ISSUE TITLE
SparkFun Qwiic LED Stick - APA102C

### ISSUE THREAD

**Issue by sfe-SparkFro** [sparkfun/pdp-qwiic-micro-python#26]
### Board

[SparkFun Qwiic LED Stick - APA102C](https://www.sparkfun.com/products/18354)

### Notes

[Arduino Library](https://github.com/sparkfun/SparkFun_Qwiic_LED_Stick_Arduino_Library)
[Python Driver](https://github.com/sparkfun/Qwiic_LED_Stick_Py)

**Comment by malcolm-sparkfun** [comment]
Made a small commit with fixes:  [5f3a5ce](https://github.com/sparkfun/Qwiic_LED_Stick_Py/commit/5f3a5ce263b2e8d47a473dd315ae16d732af6ade) and Python examples are now working
