### ISSUE TITLE
SparkFun Qwiic Twist

### ISSUE THREAD

**Issue by sfe-SparkFro** [sparkfun/pdp-qwiic-micro-python#28]
### Board

[SparkFun Qwiic Twist](https://www.sparkfun.com/products/15083)

### Notes

[Arduino Library](https://github.com/sparkfun/SparkFun_Qwiic_Twist_Arduino_Library)
[Python Driver](https://github.com/sparkfun/Qwiic_Twist_Py)

**Comment by malcolm-sparkfun** [comment]
Made some small tweaks to get this to work on micropython: 

[pull request of branch with fixes](https://github.com/sparkfun/Qwiic_Twist_Py/pull/3)

If the commits on that branch look good to a reviewer, we can merge that in and move this to done, examples looked good on the Twist.
