### ISSUE TITLE
SparkFun 6 Degrees of Freedom Breakout - LSM6DSO 

### ISSUE THREAD

**Issue by gigapod** [sparkfun/pdp-qwiic-micro-python#4]
### Board

[SparkFun 6 Degrees of Freedom Breakout - LSM6DSO ](https://www.sparkfun.com/products/18020)

### Notes
[Driver](https://github.com/sparkfun/Qwiic_LSM6DSO_Py)

**Comment by sfe-SparkFro** [comment]
Implemented a simple port of the Arduino library, which only implements the core functionality (get data and set relevant settings) without the advanced features (interrupts, FIFO, tap detection, step counting, etc.). Those can be added later if desired.

https://github.com/sparkfun/Qwiic_LSM6DSO_Py/pull/1

Tested to work on both the XRP and XBee.

**Comment by faludi** [comment]
Working well on XBee. For now the basic features are all I need so we're set.
