### ISSUE TITLE
SparkFun Qwiic Keypad - 12 Button

### ISSUE THREAD

**Issue by gigapod** [sparkfun/pdp-qwiic-micro-python#5]
### Board

[SparkFun Qwiic Keypad - 12 Button](https://www.sparkfun.com/products/15290)

### Notes
* Driver exists. - need validation [driver](https://github.com/sparkfun/Qwiic_Keypad_Py)

**Comment by faludi** [comment]
This one also seems to have issues with the new qwiic_py module. It's throwing some exceptions with my code. Going back to the older qwiic_py module fixes that, things run fine.

```
name 'IOError' isn't defined
[Errno 7019] ENODEV
```

I'm on deadline for an event right now, but can do a more complete test with the official examples later on if you need more info. Thanks!

**Comment by sfe-SparkFro** [comment]
I gave this a quick test on my end and am able to replicate it. Looks like a [similar issue to the Qwiic Button](https://github.com/sparkfun/pdp-qwiic-micro-python/issues/10), where the ACK isn't being sent correctly. Will keep the discussion in the other thread for now.
