### ISSUE TITLE
SparkFun Capacitive Touch Slider - CAP1203 

### ISSUE THREAD

**Issue by gigapod** [sparkfun/pdp-qwiic-micro-python#8]
### Board

[SparkFun Capacitive Touch Slider - CAP1203 ](https://www.sparkfun.com/products/15344)

### Notes
[Driver](https://github.com/sparkfun/Qwiic_CAP1203_Py)

**Comment by sfe-SparkFro** [comment]
@faludi FYI the Qwiic_I2C_Py library is about to get the update that resolves this. Ended up changing more than just changing the ping behavior, so it will be included in the v1.0.0 release of that library. See here: https://github.com/sparkfun/Qwiic_I2C_Py/pull/16

**Comment by faludi** [comment]
Confirmed working on XBee. This particular device lives at Digi HQ in Minneapolis, so all firmware and file updates had to be executed remotely. Zip-zap, it has a new brain and is running great! IoT does have its awesome moments.
